name: CI / Build and Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1

jobs:
  build:
    name: Build (Java 17)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Make Maven wrapper executable
        run: |
          if [ -f mvnw ]; then chmod +x mvnw; fi

      - name: Build with Maven (skip tests)
        run: ./mvnw -B -DskipTests package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target/*.jar

  deploy:
    name: Deploy to Elastic Beanstalk
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: dist

      - name: Verify artifact
        run: |
          echo "Listing dist contents..."
          ls -lh dist
          JAR_FILE=$(ls dist/*.jar | head -n 1)
          echo "Found JAR: $JAR_FILE"
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          application_name: "Springboot-store-payment-app"
          environment_name: "Springboot-store-payment-app-env"
          version_label: ${{ github.sha }}
          deployment_package: ${{ env.JAR_FILE }}
          wait_for_deployment: true
